server.port=8080

# ==========================================
# CONFIGURACIÓN DE CONEXIÓN A POSTGRESQL
# ==========================================
# ¿Por qué utilizamos la sintaxis ${VARIABLE:valor_por_defecto}?
# - Esta notación de Spring Boot permite que la aplicación sea sumamente flexible y adaptable a distintos entornos:
#   1. Desarrollo local (IntelliJ / Maven directo en Windows): Si no se define la variable de entorno SPRING_DATASOURCE_URL,
#      la aplicación toma por defecto `localhost:5433`, conectándose al puerto expuesto del contenedor Docker de Postgres.
#   2. Entorno contenerizado (Docker Compose): En el archivo docker-compose.yml inyectamos la variable de entorno 
#      `SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/citasdb`, sobrescribiendo automáticamente el valor por defecto
#      para que el backend se comunique con el servicio de base de datos dentro de la red interna de Docker ("citas-network").
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/citasdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgrespassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACIÓN DEL SERVICIO DE CORREO (Mailtrap Sandbox)
# ==========================================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=0b8cbef8982ce7
spring.mail.password=cff5ccc91d2ae8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.mail.from=noreply@sistemacitas.com
