version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres-db:
    image: postgres:16-alpine
    container_name: citas-postgres
    environment:
      POSTGRES_DB: citasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5433:5432" # Expone el puerto 5433 en el host para herramientas de base de datos externas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - citas-network
    restart: unless-stopped

  # Servidor Backend (Spring Boot)
  backend:
    build: .
    container_name: citas-backend
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/citasdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgrespassword
    networks:
      - citas-network
    restart: unless-stopped

  # Servidor Frontend (React + Nginx)
  frontend:
    build: ./frontend
    container_name: citas-frontend
    depends_on:
      - backend
    ports:
      - "5173:80" # Mapea el puerto 80 del Nginx interno al puerto 5173 del host
    networks:
      - citas-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  citas-network:
    driver: bridge
